name: diffusion
channels:
- defaults
- conda-forge
dependencies:
- python=3.6.5
- pip>=18.0
- conda>=4.5.9
- patchelf=0.9
- pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - -r requirements.txt